dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: uuB4lyPU2fKXQm3NoarivrZxVRVr6Ss+HV4C6rrxd6czMr6+hJ5lRUp0mDJsA6K4ygIZX7R7Tppjf7QXJ5vUsJ7jOn2d3/eUQkcimOIzF1lMwc691Xm8fzbHLhXv4ajxRD6IepDcGtCCASMy2LMoHI3lQ/Tc4njrlipsPxCCJUkbv8ZENUvE27igPpIv7u9tIdwn+rZmo7aY8eU9I7i4J75BzPzTvE5ZZZKJAPySSt6fBZbu6Lba7C+Ig3Ue4eye+marvUusAQFr1ghsC5H2noWnVzVg8Y5930zJLHxFY41wvWRibJHwKKtrYcW+VC1tWRf9mc8Vj0rLL0cjBHHthmYMJC7CxYjmm6Ey8tbwaFZLN0NL7m1P1LbwtCuwYt+m53+0m7lvNz2RyZDNOX/N3dLtALWYE9m1spymfgLG/KTYwndqJkdyyXfxcD1LKmB/NQCuIMcZ5YHmAeZ+jtpNMVvuDDh4KuqhIJE9XMtGpSfdXjgbhxqEUp7c9niLavrZZoskpWbGYwo537pN/ZHa0Lvhn/jgQuraMCtoHxPmkrFbARU71qRdU6E9r0IWpVUkWbWhgLA5WTIvdMbQhBUo2hBxwlvwnjC/sUpuA9zYUZv0JdyxXrSQhFXhw4GdafP6WYYlJwI3nnndNfWXdEKc16pxyrHUJToF626/O6NxAPc=
  - secure: LtllbzhXLr5iEj3Xfow4dJkLyPu9nllbpNcUvM/crgu1T4iwSTckOfNzKImJNfMAP9bY2D68UZbVd+BkpuqeRH7wFirdganTBAS8MaQd57YgTUm4c9p3Ot/p4276P3uU+CLHjUTeCOG1PBFC5nJBj4FSFx6YJXZtXMThsJ5NGPwcD7XLRHlTa69cQ9c6k8tfCXxkfq7wtFhQzyXA5AABiL+Sgjp5ZmXZM/LJhcL6r1PLv7tFGXAGkJv7bnt0vAmfL7fI29nDiWb8fXT9wJ5FMzCERBcfzKhR+kdjRNcfNoK+s4AF13ouS3tKsFX04NNCcZXXcf+BGpPAhnBpcLi+b8zfDwEIIFO0mfYG9rHCQq7qF2Z/bZXnfx/yJgIzym7ovTUvonZzwmQU9MYfGA/kdA8TB9bgy5ceeu/HMARbenPDt180tDQ0MaWTDDCdwF+LAlOEjlggMa5+KzTuRTJngIqeoqyDDlfVpsKQczomNutHBHzj0+4KtQjMGGlVmy0kpTOin1PUQp8fRz8IwlZgzhN6A43GB7m13ahBdbDQF07SjPtp+wcOHMKuaf3j4sgpp09q9hTvE5tKRTJXpq3QDzGzr+lzaWk197xBHmqKLAsLbCYgoorTymVcbSjITGii0Hk4pT6bI79QyGjluKWltszTmMStPt7AKJubxmNBINQ=
  - secure: GapNUlc9StSeVcfYWnXDfzTwGxHtCptSLQxZcNv/7H28UDQInezu+qgJGL+RZyyKQvZslJ5REZxgdKbbnvPDXJkeB5WKOJZwIFGMizJMmW9lXbO1DiXSNOVhLLVC/MtV1L6LMcmjkzbuyZgB0mSPt7yalHNfvR/JtNYAhvQrhO/z2Xn96NgZlWuMtdBgFssIgPaSiZru7kUGCkSWBNG1TW3pOTEzumzi9oQe1HxZckMilmJvI9WKSJSSuPYWdXvRLiBp+vOe/yoMD+UP48P0VBYWNM+cXFnpQh7l7B2IvngLwuIGK/8YchlZdIBEGetP1tc4eRljT24hyidBZQkOz7K0dulH7m4VlHbd6mP+/VEJairVK9z8IEjNLl2TVqTl5SSYubKS0YPHxNd3YH8Fg7TyDcc5sZJ8V1xqqbM6SwNw4YRofE/8fHTDRR7arj0Pl0Jj6QHAPAEV+2evYcuThdrZkYWq5Z9PyiOlrkN1/j6rvZj3rCqdk7Duu+t2qOMP1LbUPipcn2GGGthFj05pP2VT4MwUWd8nOs1dwghd9T0b85fqK6Y9EVioqI9NUdU2bQaDH4Thc4tQd6MIf6nmho61VWtOemBgXHMWC60h7rdtHAJhMwfOJpzurbBE7rSzbZKLZajHxbK2oLSoa2FWLqou0vfdsB6UvejcbRwB3jk=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
